---
title: "Econometric Consulting Office Hours"
output: html_document
---

Due to a persistent interest in keeping on top of current issues in econometrics, I will be holding free weekly virtual office hours open to anybody in the world with Econometrics or Statistics problems they think I can help with. I will commit only to the scheduled time, and will start first come first serve, but I will take reservations by email, form, or social media message: 

Email: <rachelleahchilders@gmail.com> or Sign up form: <https://forms.gle/tSk48w1msZgrCUqX8>

Twitter: [@donskerclass](https://twitter.com/DonskerClass) Bluesky: [@donskerclass](https://bsky.app/profile/donskerclass.bsky.social) Mastodon: [@childers@bayes.club](https://bayes.club/@childers)

Time: Wednesdays 3:30-5:30PM Central European Time (GMT +1) (US EDT 10:30AM-12:30PM/9:30-11:30AM EST) (or by appointment)

Location: Zoom: <https://uzh.zoom.us/j/64132987908?pwd=OzmlySLA3A3cjZz6RX7ibIuLoeJayU.1>

Who: Anyone. Grad students, researchers, government workers. Private sector is okay but in that case if your question requires work that exceeds the allotted time I may request to negotiate a consulting fee.

What I can probably help with: Theory questions. Research design. Modeling.

Particular expertise: Time series. Causal inference. Bayes. Structural approaches. Machine learning.

Theory: Asymptotics. Statistical learning. Bayes/MCMC. Identification. Decision theory. Semiparametrics.

Fields: I know most about macro (DSGE, heterogeneous agents, VARs, etc), but can follow along in finance and applied micro (labor, development, health, etc).

Code: I think in R, can write Julia, and can get by in Python. I am likely to suggest you build a model in Stan. I know Stata but if it's relevant to your question I suspect you can get better help elsewhere.

Questions you might want to think about/prepare in your reservation email if you want a thoughtful and well-considered response from me:

- Theory questions: 
  - State the assumptions and question setup as precisely as you can. 
  - Add references if there's a concept on which you are building.
- Design and modeling questions:
  - What is your research question?
  - What kind of data do you anticipate using to answer the question?
  - How are the variables you care about operationalized and measured in that data?
- Causal questions:
  - Who or what process determines the treatment? What are they thinking and why?
  - What is known about determinants of the outcome? Where might the treatment enter in?
  - If you are coming in with a particular estimation strategy (eg IV, DiD, etc), why do you think the assumptions are reasonable in your setting?
  - Proper understanding of the answers of the above questions should in most cases make you at best ambivalent about DiD. If you still think you have a DiD problem, expect me to try to help you figure out what else you should do.
  
Any leg work you can do is helpful. If working with data, summary stats, plots, basic regressions. For causal questions, draw a plausible DAG. For questions with an economic background, sketch elements you might want in a model: are there decisions being made? people interacting through markets? I don't expect a dissertation, and probably won't read more than about a page per request anyway. A single line question could be enough if it's clearly explained.
  






